=== Juan-D07/ProyectoDAW/Daw1/JMDPLMSGIProyectoLMSGI/ut4/05/01.dtd
<!ELEMENT grupo (estudiante+)>
<!ATTLIST grupo xmlns:xsi CDATA #IMPLIED
                            xsi:noNamespaceSchemaLocation CDATA #IMPLIED>


<!ELEMENT estudiante (nombre)>
<!ATTLIST estudiante codEstudinate ID #REQUIRED
                    codTutor1 IDREF #IMPLIED
                    codTutor2 IDREF #IMPLIED>

<!ELEMENT nombre (#PCDATA)>

=== Juan-D07/ProyectoDAW/Daw1/JMDPLMSGIProyectoLMSGI/ut4/05/01.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE grupo SYSTEM "01.dtd">

<grupo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="01.xsd">
  <estudiante codEstudinate="e1" codTutor1="e4" codTutor2="e2">
    <nombre>
      Juan Miguel Dominguez
    </nombre>
  </estudiante>
  <estudiante codEstudinate="e2" codTutor1="e4">
    <nombre>
      Juan Rivera
    </nombre>
  </estudiante>
  <estudiante codEstudinate="e3" codTutor1="e4">
    <nombre>
      Moises Dominguez
    </nombre>
  </estudiante>
  <estudiante codEstudinate="e4">
    <nombre>
      Eraclio
    </nombre>
  </estudiante>
</grupo>
