=== Juan-D07/ProyectoDAW/Daw1/JMDPLMSGIProyectoLMSGI/ut4/03/01.dtd
<!ELEMENT programingLanguges (languaje+)>
<!ATTLIST programingLanguges xmlns:xsi CDATA #IMPLIED
                            xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT languaje (description, example)>

<!ATTLIST languaje name ID #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT example (#PCDATA)>

=== Juan-D07/ProyectoDAW/Daw1/JMDPLMSGIProyectoLMSGI/ut4/03/01.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE programingLanguges SYSTEM "01.dtd">

<?xml-stylesheet href="estilos.css" type="text/css"?>

<programingLanguges xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="01.xsd">
  <languaje name="java">
    <description>
      Java es un lenguaje de programación que es ampliamente utilizado en aplicaciones empresariales y móviles.
    </description>
    <example><![CDATA[ 
    public class HolaMundo{
      public static void main(String[]  args){
          System.out.println("HolaMundo");
      }
    }
    ]]></example>
  </languaje>
    <languaje name="javascript">
    <description>
      JavaScript es un lenguaje de programación que se utiliza para crear contenido dinámico en la web.
    </description>
    <example><![CDATA[ 
    function saludo() {
      alert("¡Hola, Mundo!");
    }
      
    saludo();
    ]]></example>
  </languaje>
    <languaje name="python">
    <description>
      Python es un lenguaje de programación interpretado, de alto nivel y de propósito general.
    </description>
    <example><![CDATA[ 
    def saludo():
      print("¡Hola, Mundo!")
    
    saludo()
    ]]></example>
  </languaje>
    <languaje name="c">
    <description>
      C++ es un lenguaje de programación conocido por su eficiencia y uso en aplicaciones de alto rendimiento.
    </description>
    <example><![CDATA[ 
    #include <iostream>
    using namespace std;
      
    int main() {
    cout << "¡Hola, Mundo!" << endl;
    return 0;
    }
    ]]></example>
  </languaje>
  <languaje name="ruby">
    <description>
      Ruby es un lenguaje de programación dinámico y de alto nivel, conocido por su sintaxis simple y elegante.
    </description>
    <example><![CDATA[ 
    def saludo
    puts "¡Hola, Mundo!"
    end
    ]]></example>
  </languaje>
</programingLanguges>
