=== Juan-D07/ProyectoDAW/Daw1/JMDPLMSGIProyectoLMSGI/ut4/01/01.dtd
<!ELEMENT biblioteca (libro)+>
<!ATTLIST biblioteca xmlns:xsi CDATA #REQUIRED
            xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
        
<!ELEMENT libro (titulo, autores, año)>
<!ATTLIST libro idLibro ID #REQUIRED>
<!ATTLIST libro refLibro IDREFS #IMPLIED>
<!ATTLIST libro genero CDATA #IMPLIED>
<!ATTLIST libro idioma CDATA "Español">
<!ATTLIST libro formato (impreso | digital) "impreso">
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT autores (autor)+>
<!ELEMENT autor (nombre, apellido, nacionalidad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>

=== Juan-D07/ProyectoDAW/Daw1/JMDPLMSGIProyectoLMSGI/ut4/01/01.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE biblioteca SYSTEM "01.dtd">
<!-- XML Almacena Datos -->

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="01.xsd">

    <libro idLibro="l1" formato="digital" genero="Aventura">
        <titulo>Wigetta</titulo>
        <autores>
            <autor>
                <nombre> Samuel</nombre>
                <apellido> De Luque</apellido>
                <nacionalidad> Española</nacionalidad>
            </autor>
            <autor>
                <nombre> Guillermo</nombre>
                <apellido> Diaz</apellido>
                <nacionalidad> Española</nacionalidad>
            </autor>
        </autores>
        <año>2015</año>

    </libro>

    <libro idLibro="l2" genero="Autohumillacion">
        <titulo>El Libro Troll</titulo>
        <autores>
            <autor>
                <nombre> Ruben</nombre>
                <apellido> Doblas</apellido>
                <nacionalidad> Española</nacionalidad>
            </autor>
        </autores>
        <año>2014</año>

    </libro>

    <libro idLibro="l3" idioma="Koreano" genero="Restrospectivo">
        <titulo>Luna de Pluton</titulo>
        <autores>
            <autor>
                <nombre> Dross</nombre>
                <apellido> Xd</apellido>
                <nacionalidad> Venezolano</nacionalidad>
            </autor>
        </autores>
        <año>2016</año>


    </libro>

    <libro idLibro="l4" idioma="Koreano" refLibro="l3">
        <titulo>Luna de Jupiter</titulo>
        <autores>
            <autor>
                <nombre> Yo</nombre>
                <apellido> Mismo</apellido>
                <nacionalidad> Venezolano</nacionalidad>
            </autor>
        </autores>
        <año>2017</año>


    </libro>



</biblioteca>
